### ISSUE TITLE
Not compatible with mkdocstrings

### ISSUE THREAD

**Issue by kratsg** [glennmatthews/mkdocs-version-annotations#1]
### Environment
* Python version:  3.8.6
* mkdocs version: 1.2.3
* mkdocs-version-annotations version: 1.0.0

### Expected Behavior

Documenting a docstring with the version annotation renders an admonition:

```
    """
    The top-level user-facing client for interacting with the ITk Production Database API.

    +++ 0.4.0
        Added use_eos

    !!! note "Added in version 0.4.0"
        Added use_eos

    test
    """
```

### Observed Behavior

Text is not substituted / admonition is not rendered.

<img width="707" alt="Screenshot 2023-03-01 at 11 36 09 PM" src="https://user-images.githubusercontent.com/761483/222332284-daab559e-e471-4c3c-8c64-a8e036572488.png">

Note in the example, directly including an admonition in the docstring has it render correctly, so the issue is probably with *when* this package is being injected in order to parse.

**Comment by pawamoy** [comment]
This plugin replaces contents in the `on_page_markdown` event. This indeed won't work with mkdocstrings, as mkdocstrings doesn't generate Markdown, and therefore this plugin never gets access the contents of docstrings.

The only way to have both projects work together is that this plugin becomes a Markdown extension rather than a MkDocs plugin.

**Comment by glennmatthews** [comment]
Converted to a Markdown extension and released as `markdown-version-annotations` v1.0.1.

**Comment by pawamoy** [comment]
Awesome @glennmatthews!

**Comment by pawamoy** [comment]
Would you like to send a PR to update the information in the [MkDocs catalog](https://github.com/mkdocs/catalog) regarding your project?

**Comment by glennmatthews** [comment]
Thanks for the suggestion - opened https://github.com/mkdocs/catalog/pull/213 :)
